<a href="https://colab.research.google.com/github/Hazil21/leads_analysis/blob/main/Lead_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
a=pd.read_csv('/content/Unified_Leads.csv')
print(a)
print(a.shape)
print(a.size)
print("#############################")
print(a.isna().sum())
print(a.head())
print(a.tail())
print(a.dtypes)

                   Name  contact_number                    Contact_email  \
0          Anjali Singh      9931980478      anjali.singh878@hotmail.com
1            Kiran Bose      6474315136        kiran.bose601@example.com
2      Karthik Malhotra      6753707898  karthik.malhotra329@example.com
3         Anjali Sharma      9439163624      anjali.sharma85@example.com
4          Sneha Kapoor      9878269840         sneha.kapoor46@gmail.com
...                 ...             ...                              ...
27370       Rohit Reddy      6992973331       rohit.reddy220@hotmail.com
27371      Kiran Shetty      9410734029      kiran.shetty925@outlook.com
27372       Neha Shetty      9508547875         neha.shetty6@example.com
27373      Nikhil Yadav      7870690595      nikhil.yadav620@outlook.com
27374      Nikhil Reddy      8750283113        nikhil.reddy172@gmail.com

          creation_date first_call_attempt               lead_status  \
0      03-02-2026 22:31                NaN    PENDING WITH EXECUTIVE
1      03-02-2026 21:46                NaN    PENDING WITH EXECUTIVE
2      03-02-2026 21:28                NaN    PENDING WITH EXECUTIVE
3      03-02-2026 19:59                NaN    PENDING WITH EXECUTIVE
4      03-02-2026 19:19                NaN    PENDING WITH EXECUTIVE
...                 ...                ...                       ...
27370  02-06-2025 13:14   02-06-2025 14:46                    CLOSED
27371  02-06-2025 13:05                NaN                    CLOSED
27372  02-06-2025 12:39   02-06-2025 13:13                    CLOSED
27373  02-06-2025 12:35   02-06-2025 13:01  RESCHEDULED BY EXECUTIVE
27374  02-06-2025 12:35   02-06-2025 14:33  RESCHEDULED BY EXECUTIVE

               lead_stage             lead_tag assigned_to    last_call_date  \
0                Prospect                  NaN     Anshad                NaN
1                Prospect                  NaN     Anshad                NaN
2                Prospect                  NaN     Anshad                NaN
3                Prospect                  NaN     Anshad                NaN
4                Prospect                  NaN     Anshad                NaN
...                   ...                  ...         ...               ...
27370                LOST       not-interested     Riswana  02-06-2025 14:46
27371                LOST  lost-to-competition     Anshad                NaN
27372           CONVERTED                  NaN     Anshad   02-06-2025 13:13
27373  Follow Up Required                 cold     Anshad   02-06-2025 13:01
27374  Follow Up Required                 cold     Anshad   02-06-2025 14:33

      last_call_time  references            campaign_name   source_type  \
0                NaN         NaN  Data Analytics Knovista     INSTAGRAM
1                NaN         NaN  Data Analytics Knovista  FACEBOOK_ADS
2                NaN         NaN  Data Analytics Knovista     INSTAGRAM
3                NaN         NaN  Data Analytics Knovista     INSTAGRAM
4                NaN         NaN  Data Analytics Knovista     INSTAGRAM
...              ...         ...                      ...           ...
27370        2:46 PM         NaN      Business Accounting     INSTAGRAM
27371            NaN         NaN      Business Accounting     INSTAGRAM
27372        1:13 PM         NaN      Business Accounting     INSTAGRAM
27373        1:01 PM         NaN      Business Accounting     INSTAGRAM
27374        2:33 PM         NaN      Business Accounting     INSTAGRAM

        source_name
0         INSTAGRAM
1      FACEBOOK_ADS
2         INSTAGRAM
3         INSTAGRAM
4         INSTAGRAM
...             ...
27370     INSTAGRAM
27371     INSTAGRAM
27372     INSTAGRAM
27373     INSTAGRAM
27374     INSTAGRAM

[27375 rows x 15 columns]
(27375, 15)
410625
#############################
Name                      0
contact_number            0
Contact_email             0
creation_date             0
first_call_attempt     6729
lead_status               0
lead_stage                0
lead_tag              11416
assigned_to               0
last_call_date         6729
last_call_time         6729
references            27375
campaign_name             0
source_type               0
source_name               0
dtype: int64
               Name  contact_number                    Contact_email  \
0      Anjali Singh      9931980478      anjali.singh878@hotmail.com
1        Kiran Bose      6474315136        kiran.bose601@example.com
2  Karthik Malhotra      6753707898  karthik.malhotra329@example.com
3     Anjali Sharma      9439163624      anjali.sharma85@example.com
4      Sneha Kapoor      9878269840         sneha.kapoor46@gmail.com

      creation_date first_call_attempt             lead_status lead_stage  \
0  03-02-2026 22:31                NaN  PENDING WITH EXECUTIVE   Prospect
1  03-02-2026 21:46                NaN  PENDING WITH EXECUTIVE   Prospect
2  03-02-2026 21:28                NaN  PENDING WITH EXECUTIVE   Prospect
3  03-02-2026 19:59                NaN  PENDING WITH EXECUTIVE   Prospect
4  03-02-2026 19:19                NaN  PENDING WITH EXECUTIVE   Prospect

  lead_tag assigned_to last_call_date last_call_time  references  \
0      NaN     Anshad             NaN            NaN         NaN
1      NaN     Anshad             NaN            NaN         NaN
2      NaN     Anshad             NaN            NaN         NaN
3      NaN     Anshad             NaN            NaN         NaN
4      NaN     Anshad             NaN            NaN         NaN

             campaign_name   source_type   source_name
0  Data Analytics Knovista     INSTAGRAM     INSTAGRAM
1  Data Analytics Knovista  FACEBOOK_ADS  FACEBOOK_ADS
2  Data Analytics Knovista     INSTAGRAM     INSTAGRAM
3  Data Analytics Knovista     INSTAGRAM     INSTAGRAM
4  Data Analytics Knovista     INSTAGRAM     INSTAGRAM
               Name  contact_number                Contact_email  \
27370   Rohit Reddy      6992973331   rohit.reddy220@hotmail.com
27371  Kiran Shetty      9410734029  kiran.shetty925@outlook.com
27372   Neha Shetty      9508547875     neha.shetty6@example.com
27373  Nikhil Yadav      7870690595  nikhil.yadav620@outlook.com
27374  Nikhil Reddy      8750283113    nikhil.reddy172@gmail.com

          creation_date first_call_attempt               lead_status  \
27370  02-06-2025 13:14   02-06-2025 14:46                    CLOSED
27371  02-06-2025 13:05                NaN                    CLOSED
27372  02-06-2025 12:39   02-06-2025 13:13                    CLOSED
27373  02-06-2025 12:35   02-06-2025 13:01  RESCHEDULED BY EXECUTIVE
27374  02-06-2025 12:35   02-06-2025 14:33  RESCHEDULED BY EXECUTIVE

               lead_stage             lead_tag assigned_to    last_call_date  \
27370                LOST       not-interested     Riswana  02-06-2025 14:46
27371                LOST  lost-to-competition     Anshad                NaN
27372           CONVERTED                  NaN     Anshad   02-06-2025 13:13
27373  Follow Up Required                 cold     Anshad   02-06-2025 13:01
27374  Follow Up Required                 cold     Anshad   02-06-2025 14:33

      last_call_time  references        campaign_name source_type source_name
27370        2:46 PM         NaN  Business Accounting   INSTAGRAM   INSTAGRAM
27371            NaN         NaN  Business Accounting   INSTAGRAM   INSTAGRAM
27372        1:13 PM         NaN  Business Accounting   INSTAGRAM   INSTAGRAM
27373        1:01 PM         NaN  Business Accounting   INSTAGRAM   INSTAGRAM
27374        2:33 PM         NaN  Business Accounting   INSTAGRAM   INSTAGRAM
Name                   object
contact_number          int64
Contact_email          object
creation_date          object
first_call_attempt     object
lead_status            object
lead_stage             object
lead_tag               object
assigned_to            object
last_call_date         object
last_call_time         object
references            float64
campaign_name          object
source_type            object
source_name            object
dtype: object

In [ ]:
d=a.drop(['Name','contact_number','Contact_email','lead_tag','references','creation_date','first_call_attempt','last_call_date','last_call_time'],axis=1)
d

,lead_status,lead_stage,assigned_to,campaign_name,source_type,source_name
0,PENDING WITH EXECUTIVE,Prospect,Anshad,Data Analytics Knovista,INSTAGRAM,INSTAGRAM
1,PENDING WITH EXECUTIVE,Prospect,Anshad,Data Analytics Knovista,FACEBOOK_ADS,FACEBOOK_ADS
2,PENDING WITH EXECUTIVE,Prospect,Anshad,Data Analytics Knovista,INSTAGRAM,INSTAGRAM
3,PENDING WITH EXECUTIVE,Prospect,Anshad,Data Analytics Knovista,INSTAGRAM,INSTAGRAM
4,PENDING WITH EXECUTIVE,Prospect,Anshad,Data Analytics Knovista,INSTAGRAM,INSTAGRAM
...,...,...,...,...,...,...
27370,CLOSED,LOST,Riswana,Business Accounting,INSTAGRAM,INSTAGRAM
27371,CLOSED,LOST,Anshad,Business Accounting,INSTAGRAM,INSTAGRAM
27372,CLOSED,CONVERTED,Anshad,Business Accounting,INSTAGRAM,INSTAGRAM
27373,RESCHEDULED BY EXECUTIVE,Follow Up Required,Anshad,Business Accounting,INSTAGRAM,INSTAGRAM
27374,RESCHEDULED BY EXECUTIVE,Follow Up Required,Anshad,Business Accounting,INSTAGRAM,INSTAGRAM

In [ ]:
d.dtypes

lead_status      object
lead_stage       object
assigned_to      object
campaign_name    object
source_type      object
source_name      object
dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
d['lead_stage']=le.fit_transform(d['lead_stage'])
d['assigned_to']=le.fit_transform(d['assigned_to'])
d['campaign_name']=le.fit_transform(d['campaign_name'])
d['source_type']=le.fit_transform(d['source_type'])
d['source_name']=le.fit_transform(d['source_name'])
d

,lead_status,lead_stage,assigned_to,campaign_name,source_type,source_name
0,PENDING WITH EXECUTIVE,3,4,5,2,10
1,PENDING WITH EXECUTIVE,3,4,5,0,9
2,PENDING WITH EXECUTIVE,3,4,5,2,10
3,PENDING WITH EXECUTIVE,3,4,5,2,10
4,PENDING WITH EXECUTIVE,3,4,5,2,10
...,...,...,...,...,...,...
27370,CLOSED,2,16,2,2,10
27371,CLOSED,2,4,2,2,10
27372,CLOSED,0,4,2,2,10
27373,RESCHEDULED BY EXECUTIVE,1,4,2,2,10
27374,RESCHEDULED BY EXECUTIVE,1,4,2,2,10

In [ ]:
d['lead_status']=d['lead_status'].apply(lambda x: 1 if x == 'CLOSED' else 0)
d

,lead_status,lead_stage,assigned_to,campaign_name,source_type,source_name
0,0,3,4,5,2,10
1,0,3,4,5,0,9
2,0,3,4,5,2,10
3,0,3,4,5,2,10
4,0,3,4,5,2,10
...,...,...,...,...,...,...
27370,1,2,16,2,2,10
27371,1,2,4,2,2,10
27372,1,0,4,2,2,10
27373,0,1,4,2,2,10
27374,0,1,4,2,2,10

In [ ]:
x=d.iloc[:,1:].values
x

array([[ 3,  4,  5,  2, 10],
       [ 3,  4,  5,  0,  9],
       [ 3,  4,  5,  2, 10],
       ...,
       [ 0,  4,  2,  2, 10],
       [ 1,  4,  2,  2, 10],
       [ 1,  4,  2,  2, 10]])

In [ ]:
y=d.iloc[:,:1].values
y

array([[0],
       [0],
       [0],
       ...,
       [1],
       [0],
       [0]])

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.30)
xtrain

array([[ 3, 22,  5,  2, 10],
       [ 3,  4, 15,  1, 23],
       [ 2, 16,  2,  2, 10],
       ...,
       [ 1,  4,  0,  2, 10],
       [ 2, 13,  2,  2, 10],
       [ 2, 13, 13,  0,  9]])

In [ ]:
ytrain

array([[0],
       [0],
       [1],
       ...,
       [0],
       [1],
       [1]])

In [ ]:
xtest

array([[ 3, 10,  6,  2, 10],
       [ 2, 15, 13,  2, 10],
       [ 3, 22,  5,  2, 10],
       ...,
       [ 2,  6,  0,  2, 10],
       [ 3,  3,  0,  2, 10],
       [ 2,  3,  0,  2, 10]])

In [ ]:
ytest

array([[0],
       [1],
       [0],
       ...,
       [1],
       [0],
       [1]])

In [ ]:
from sklearn.preprocessing import StandardScaler
s=StandardScaler()
s.fit(xtest)
xtrain=s.transform(xtrain)
xtest=s.transform(xtest)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
xtrain=scaler.fit_transform(xtrain)
xtest=scaler.transform(xtest)

In [ ]:
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
svm_model=SVC()
nb_model=MultinomialNB()
knn_model=KNeighborsClassifier(n_neighbors=7)
rf_model=RandomForestClassifier(n_estimators=100)
dt_model=DecisionTreeClassifier()
lstmodel=[svm_model,nb_model,knn_model,rf_model,dt_model]

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score,roc_auc_score
for i in lstmodel:
  print(i)
  i.fit(xtrain,ytrain)
  ypred=i.predict(xtest)
  ac=accuracy_score(ypred,ytest)
  roc=roc_auc_score(ypred,ytest)
  print("######################")
  print(classification_report(ypred,ytest))
  print("accuracy score",ac)
  print("roc auc score",roc)
  print("******************************")

SVC()

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

######################
              precision    recall  f1-score   support

           0       0.98      0.99      0.99      4440
           1       0.99      0.97      0.98      3773

    accuracy                           0.98      8213
   macro avg       0.99      0.98      0.98      8213
weighted avg       0.98      0.98      0.98      8213

accuracy score 0.9844149519055156
roc auc score 0.9835350689942527
******************************
MultinomialNB()
######################
              precision    recall  f1-score   support

           0       0.91      0.55      0.69      7420
           1       0.10      0.48      0.17       793

    accuracy                           0.55      8213
   macro avg       0.51      0.52      0.43      8213
weighted avg       0.83      0.55      0.64      8213

accuracy score 0.5468160233775722
roc auc score 0.5183074271846311
******************************
KNeighborsClassifier(n_neighbors=7)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/neighbors/_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

######################
              precision    recall  f1-score   support

           0       0.98      0.99      0.98      4470
           1       0.98      0.97      0.98      3743

    accuracy                           0.98      8213
   macro avg       0.98      0.98      0.98      8213
weighted avg       0.98      0.98      0.98      8213

accuracy score 0.9805186898818946
roc auc score 0.9798434183779894
******************************
RandomForestClassifier()

/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

######################
              precision    recall  f1-score   support

           0       0.98      0.99      0.99      4442
           1       0.99      0.97      0.98      3771

    accuracy                           0.98      8213
   macro avg       0.98      0.98      0.98      8213
weighted avg       0.98      0.98      0.98      8213

accuracy score 0.9841714355290393
roc auc score 0.9833039735100129
******************************
DecisionTreeClassifier()
######################
              precision    recall  f1-score   support

           0       0.98      0.99      0.98      4448
           1       0.99      0.97      0.98      3765

    accuracy                           0.98      8213
   macro avg       0.98      0.98      0.98      8213
weighted avg       0.98      0.98      0.98      8213

accuracy score 0.9834408863996104
roc auc score 0.9826118487679976
******************************

In [ ]:
from sklearn.metrics import accuracy_score,roc_auc_score
roc=roc_auc_score(ypred,ytest)
print(roc)
ac=accuracy_score(ypred,ytest)
print(ac)

0.9826118487679976
0.9834408863996104

In [ ]:
print(rf_model.predict([[0,4,2,2,10]]))

[1]